name: kiss_layout
description: "A simple system for standardizing layout in flutter"
version: 1.1.0
homepage: https://github.com/WAMF/kiss_layout

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

flutter:

